###
https://dummyjson.com/products

###
https://dummyjson.com/products?limit=10&skip=10&select=title,price

###
POST https://dummyjson.com/products/add
Content-Type: application/json

{
  "title": "New Product",
  "price": 100
}

###
POST http://localhost:3000/products